subsystems:
    drivetrain:
        implemented: false
        falcons:
            leftMain: -1
            leftFollower: -1
            rightMain: -1
            rightFollower: -1
        constants:
            pigeonId: -1
            pigeonOnTalon: -1
            kP: 0
            kI: 0
            kD: 0
            kF: 0
            encPPR: 0
            currentFloorCheck: .12
            currentEpsilonCheck: .2
            rpmFloorCheck: 2000
            rpmEpsilonCheck: 60
            openLoopRampRate: 1
    climber:
        implemented: false
        talons:
            elevator: 0
    collector:
        implemented: false
        talons:
            intake: -1
        solenoids:
            arm: -1
    hopper:
        implemented: false
        talon:
            spindexer: -1
        solenoids:
            arm: -1 # should find a better name - not really an "arm"
    shooter:
        implemented: false
        talons:
            shootMaster: 2
            shootFollowerA: 4
            shootFollowerB: 10
            shootFollowerC: 11
        solenoids:
            hood: -1
        constants: #TODO: need tuning
            kP: 0
            kI: 0
            kD: 0
            kF: 0
    turret:
        implemented: false
        talons:
            turret: -1
    canifier:
        implemented: false
        constants:
            canId: 0
    ledmanager:
        implemented: false
        canifier: 0
pcm: 0
constants: #TODO: update constants for new robot
    wheelDiameter: 6.25 #inches
    trackWidth: 25 #inches
    maxVel: 40 #inch/s
    maxAccel: 80 #inch/s^2
    sensorPhase: 0
    kLooperDt: .030
    kTrackScrubFactor: 1.0
    kPCMId: 0
    pathKs: 2
    verbose: 0
