subsystems:
<<<<<<< HEAD
    drivetrain:
        implemented: true
        falcons:
            leftMain: 17
            leftFollower: 1
            leftFollowerTwo: -1
            rightMain: 14
            rightFollower: 15
            rightFollowerTwo: -1
        invertMotor:
            - 17
        constants:
            pigeonId: 9
            pigeonOnTalon: -1
            kP: 0.1 # 0.18 # TODO: tune PID, these are temporary PID values from Zeta
            kI: 0.01 # 0.018
            kD: 5.0 # 3.6
            kF: 0.0475813
            iZone: 0
            encPPR: 22220.8
            currentFloorCheck: .12
            currentEpsilonCheck: .2
            rpmFloorCheck: 2000
            rpmEpsilonCheck: 60
            openLoopRampRate: 0.8
    climber:
        implemented: false
        talons:
            elevator: 12
        solenoids:
            deployer: 5
    collector:
        implemented: true
        talons:
            intake: 11
        solenoids:
            arm: 0
        constants:
            kP: 0.2
            kI: 0
            kD: 0
            kF: 0
    hopper:
        implemented: true
        talons:
            spindexer: 4
            elevator: 5
        invertMotor:
            - 4
        solenoids:
            feederFlap: 4
    shooter:
        implemented: true
        falcons:
            shooterMaster: 3
            shooterFollowerB: 2
        talons:
            shooterFollowerA: -1 # 3
            shooterFollowerC: -1 # 2
=======
    turret:
>>>>>>> master
        constants:
            kP: 0.15 #0.30
            kI: 0
            kD: 2.5 #4.5
            kF: 0.053 #0.00953253
            currentFloorCheck: .12
            currentEpsilonCheck: .2
            rpmFloorCheck: 2000
            rpmEpsilonCheck: 60
            velocityThreshold: 500
    turret:
        implemented: true
        talons:
            turret: 10
        constants: # TODO: tune [P, I, D]
            kP: 2.83
            kI: 0 #0.0003
            kD: 0
            kF: 0 # Should be 0 for position control
            encPPR: 4124.6
            minPos: -4220
            maxPos: -1072
    ledmanager:
        implemented: false
        canifier: 0
pcm: 8
constants: #TODO: update constants for new robot
    wheelDiameter: 6.15 #inches
    trackWidth: 25 #inches
    maxVel: 110 #inch/s
    maxAccel: 40 #inch/s^2
    sensorPhase: 0
    kLooperDt: .030
    kTrackScrubFactor: 1.0
    pathKs: 2
    verbose: 0 # O or 1
    compressorEnabled: 1 # 0 or 1
    badLogEnabled: 1
    logTeleOp: 1
    useAutoAim: 1
