$extends: zodiac_base
subsystems:
    climber:
        implemented: true
    hopper:
        invertMotor:
            - 5
<<<<<<< HEAD
=======
    shooter:
        falcons:
            shooterMain: 3
            shooterFollower: 2
>>>>>>> master
    turret:
        constants:
            minPos: -3802
            maxPos: -757
    ledmanager:
        implemented: true
        canifier: 18
    camera:
        implemented: true
        canifier: 19
constants:
    wheelDiameter: 6.32 #inches
