$extends: zodiac_base
subsystems:
    shooter:
        falcons:
            shooterMaster: 3
            shooterFollowerB: 2
    turret:
        constants:
            minPos: -4220
            maxPos: -1072
constants:
    wheelDiameter: 6.15 #inches
