subsystems:
    drivetrain:
        implemented: true
        falcons:
            leftMain: 17
            leftFollower: 1
            leftFollowerTwo: -1
            rightMain: 14
            rightFollower: 15
            rightFollowerTwo: -1
        invertMotor:
            - 17
        constants:
            pigeonId: 10
            pigeonOnTalon: -1
            kP: 0.13 # 0.18 # TODO: tune PID, these are temporary PID values from Zeta
            kI: 0.013 # 0.018
            kD: 4.0 # 3.6
            kF: 0.0475813
            iZone: 0
            encPPR: 22220.8
            currentFloorCheck: .12
            currentEpsilonCheck: .2
            rpmFloorCheck: 2000
            rpmEpsilonCheck: 60
            openLoopRampRate: 1
    climber:
        implemented: false
        talons:
            elevator: 0
    collector:
        implemented: false
        talons:
            intake: 11
        solenoids:
            arm: 0
        constants:
            kP: 0.2
            kI: 0
            kD: 0
            kF: 0
    hopper:
        implemented: true
        talons:
            spindexer: 12
            elevator: 2
        invertMotor:
            - 12
        solenoids:
            feederFlap: -1
    shooter:
        implemented: true
        talons:
            shooterMaster: 20
            shooterFollowerA: 3
            shooterFollowerB: 4
            shooterFollowerC: 5
        constants: #TODO: need tuning [P, I, D]
            kP: 0.025
            kI: 0
            kD: 1
            kF: 0.00953253
            currentFloorCheck: .12
            currentEpsilonCheck: .2
            rpmFloorCheck: 2000
            rpmEpsilonCheck: 60
    turret:
        implemented: true
        talons:
            turret: 13
        constants: # TODO: tune [P, I, D]
            kP: 2.85
            kI: 0
            kD: 0
            kF: 0 # Should be 0 for position control
            encPPR: 4124.6
            minPos: -2617
            maxPos: -1101
    ledmanager:
        implemented: false
        canifier: 0
pcm: 8
constants: #TODO: update constants for new robot
    wheelDiameter: 6.29 #inches
    trackWidth: 25 #inches
    maxVel: 120 #inch/s
    maxAccel: 40 #inch/s^2
    sensorPhase: 0
    kLooperDt: .030
    kTrackScrubFactor: 1.0
    pathKs: 2
    verbose: 0 # O or 1
    compressorEnabled: 1 # 0 or 1
