$extends: zodiac_base
subsystems:
    climber:
        implemented: true
    hopper:
        invertMotor:
            - elevator
    shooter:
        falcons:
            shooterMain: 3
            shooterFollower: 2
    turret:
        constants:
            minPos: -4445
            maxPos: -1273
    ledmanager:
        implemented: true
        canifier: 18
    camera:
        implemented: true
        canifier: 19
constants:
    wheelDiameter: 6.32 #inches
