subsystems:
    drivetrain:
        implemented: true
        falcons:
            leftMain: 17
            leftFollower: 1
            leftFollowerTwo: -1
            rightMain: 14
            rightFollower: 15
            rightFollowerTwo: -1
        invertMotor:
            - 17
        constants:
            pigeonId: 10
            pigeonOnTalon: -1
            kP: 0.09 # TODO: tune PID, these are temporary PID values from Zeta
            kI: 0.018
            kD: 3.6
            kF: 0.0475813
            iZone: 0
            encPPR: 22220.8
            currentFloorCheck: .12
            currentEpsilonCheck: .2
            rpmFloorCheck: 2000
            rpmEpsilonCheck: 60
            openLoopRampRate: 1
    climber:
        implemented: false
        talons:
            elevator: 0
    collector:
        implemented: true
        talons:
            intake: 11
        solenoids:
            arm: -1
    hopper:
        implemented: true
        talons:
            spindexer: 12
            elevator: 2
        invertMotor:
            - 12
            - 2
        solenoids:
            feederFlap: -1 # should find a better name - not really an "arm"
    shooter:
        implemented: false
        talons:
            shooterMaster: -1
            shooterFollowerA: -1
            shooterFollowerB: -1
            shooterFollowerC: -1
        constants: #TODO: need tuning [P, I, D]
            kP: 0.025
            kI: 0
            kD: 1
            kF: 0.00953253
            currentFloorCheck: .12
            currentEpsilonCheck: .2
            rpmFloorCheck: 2000
            rpmEpsilonCheck: 60
    turret:
        implemented: true
        talons:
            turret: 13
        constants: # TODO: tune [P, I, D]
            kP: 0
            kI: 0
            kD: 0
            kF: 0 # Should be 0 for position control
            encPPR: 2062.3
    ledmanager:
        implemented: false
        canifier: 0
pcm: -1 # 8
constants: #TODO: update constants for new robot
    wheelDiameter: 6.25 #inches
    trackWidth: 25 #inches
    maxVel: 40 #inch/s
    maxAccel: 80 #inch/s^2
    sensorPhase: 0
    kLooperDt: .030
    kTrackScrubFactor: 1.0
    pathKs: 2
    verbose: 0
