subsystems:
    drivetrain: #TODO: tuning and measure encPPR
        implemented: true
        falcons:
            leftMain: 14
            leftFollower: 15
            rightMain: 0
            rightFollower: 1
        invertMotor:
            - 14
        constants:
            pigeonId: -1
            pigeonOnTalon: -1
            kP: 0
            kI: 0
            kD: 0
            kF: 0.0475813
            iZone: 0
            encPPR: 0
            currentFloorCheck: .12
            currentEpsilonCheck: .2
            rpmFloorCheck: 2000
            rpmEpsilonCheck: 60
            openLoopRampRate: 1
    climber:
        implemented: false
        talons:
            elevator: 0
    collector:
        implemented: false
        talons:
            intake: -1
        solenoids:
            arm: -1
    hopper:
        implemented: false
        talon:
            spindexer: -1
            elevator: -1
        solenoids:
            arm: -1 # should find a better name - not really an "arm"
    shooter:
        implemented: false
        talons:
            shooterMaster: 2
            shooterFollowerA: 4
            shooterFollowerB: 10
            shooterFollowerC: 11
        invertMotor:
            - 2
        solenoids:
            hood: -1
        constants: #TODO: need tuning [P, I, D]
            kP: 0.025
            kI: 0
            kD: 1
            kF: 0.00953253
            currentFloorCheck: .12
            currentEpsilonCheck: .2
            rpmFloorCheck: 2000
            rpmEpsilonCheck: 60
    turret: #TODO: need to measure encPPR
        implemented: false
        talons:
            turret: -1
        constants:
            encPPR: 0
    canifier:
        implemented: false
        constants:
            canId: 0
    ledmanager:
        implemented: false
        canifier: 0
pcm: 0
constants: #TODO: update constants for new robot
    wheelDiameter: 6.25 #inches
    trackWidth: 25 #inches
    maxVel: 40 #inch/s
    maxAccel: 80 #inch/s^2
    kLooperDt: .030
    kTrackScrubFactor: 1.0
    kPCMId: 0
    pathKs: 2
    verbose: 0
